SCHEMAS = {
    "customers": {
        "customer_id": "VARCHAR(50)",
        "gender": "VARCHAR(100)",
        "age": "INT",
        "country": "VARCHAR(100)",
        "region": "VARCHAR(100)",
        "city": "VARCHAR(100)",
        "acquisition_date": "DATE",
        "acquisition_channel": "VARCHAR(250)",
        "acquisition_campaign": "VARCHAR(100)",
    },
    "products": {
        "product_id": "VARCHAR(50)",
        "product_name": "VARCHAR(255)",
        "price": "DECIMAL(12,2)",
        "sub_category": "VARCHAR(100)",
        "category": "VARCHAR(100)",
        "brand": "VARCHAR(255)",
        "supplier_id": "VARCHAR(50)",
        "unit_cost": "DECIMAL(12,2)",
    },
    "campaigns": {
        "campaign_id": "VARCHAR(50)",
        "campaign_type": "VARCHAR(100)",
        "channel": "VARCHAR(100)",
        "start_date": "DATE",
        "end_date": "DATE",
        "total_revenue": "DECIMAL(12,2)",
        "campaign_name": "VARCHAR(255)",
        "budget": "DECIMAL(12,2)",
        "campaign_objective": "VARCHAR(100)",
    },
    "marketing": {
        "ads_id": "VARCHAR(50)",
        "campaign_id": "VARCHAR(50)",
        "channel_name": "VARCHAR(255)",
        "date": "DATE",
        "ad_spend": "DECIMAL(12,2)",
        "impressions": "INT",
        "clicks": "INT",
        "conversions": "INT",
        "campaign_type": "VARCHAR(100)",
        "campaign_objective": "VARCHAR(100)",
    },
    "channels": {
        "channel_name": "VARCHAR(255)",
        "channel_category": "VARCHAR(100)",
        "traffic_type": "VARCHAR(100)",
    },
    "sales": {
        "order_id": "VARCHAR(50)",
        "customer_id": "VARCHAR(50)",
        "customer_status": "VARCHAR(50)",
        "product_id": "VARCHAR(50)",
        "product_name": "VARCHAR(255)",
        "category": "VARCHAR(255)",
        "ship_mode": "VARCHAR(100)",
        "quantity": "INT",
        "discount": "DECIMAL(12,2)",
        "unit_cost": "DECIMAL(12,2)",
        "price": "DECIMAL(12,2)",
        "refund_status": "VARCHAR(100)",
        "revenue": "DECIMAL(12,2)",
        "order_date": "DATE",
        "channel": "VARCHAR(100)",
        "campaign_id": "VARCHAR(50)",
    },
}
